### ISSUE TITLE
Tube should have mounting hardware, space for sensors, solar panels etc.

### ISSUE THREAD

**Issue by annerajb** [OpenHyperloop/OpenHyperloop#1]
Looking at the tubes wiki page.
It should have some additional requirements.

Be able to host the magnets that will move the train forward.
A place for sensors for air pressure, if there is something on this tube section?, etc.
A place to attach on the top the solar panels.
A section on the side to host electronic like inverter for the solar panels, battery, wiring etc.
It should have a cable conduit to be able to transport commands and telemetry for that tube section transport command can control magnets on the tube section, give feedback on how much energy is being gathered by the solar panel.

**Comment by OpenHyperloop** [comment]
Excellent Points!

The tubes as described by Elon are 10' 10" wide on the interior (presumably), smooth, and 1" thick, so all the magnets, sensors, cables, etc would have to be outside that smooth area.  I'm thinking that a compartment on the bottom area should be able to hold most of those components, and a track for the cables.  This would be cheaper than making a full hollow area on the outside of the tube.

Not to mention the tubes still need some sort of emergency hatch.

Regarding the solar panels, I believe I mention the attachment of the solar panels via the hook components on the top (See diagram on the [Tube](https://github.com/OpenHyperloop/OpenHyperloop/wiki/Tubes) page).

**Comment by OpenHyperloop** [comment]
I have updated the wiki with these concerns and updated the sketch to show the mounting hardware better.
