### ISSUE TITLE
Some reference for operating costs.

### ISSUE THREAD

**Issue by BrianChapman** [OpenHyperloop/OpenHyperloop#2]
Wikipedia: "In 2005, BART required nearly $300 million in funds after fares. About 37% of the costs went to maintenance, 29% to actual transportation operations, 24% to general administration, 8% to police services, and 4% to construction and engineering. "

It seems that operating and maintenance costs might be quite a bit higher than your projections. Granted BART is a different system, with lots of stations, and lots of bureaucracy. I'd say your looking at 100-200 million/year in operating costs just using a high level interpolation.

Also, from prior experience with engineering projects, especially ambitious ones like this, I'd count on a 2x to 4x multiplier on any cost estimate put out there.

**Comment by OpenHyperloop** [comment]
Thanks for the comparison!  I've updated the business models page with the BART numbers.  I also try to put the numbers in context (with comparison of miles of track, number of vehicles, and number of stations).

I also acknowledge the estimate to double the estimated expense numbers.
