### ISSUE TITLE
Car Doors

### ISSUE THREAD

**Issue by rlarno** [OpenHyperloop/OpenHyperloop#3]
To load/unload cars and cargo, I'd suggest to look at systems similar to how air cargo is loaded. So a sort of tray that can be prepared and rolled into the actual pod.

Cars could drive onto the tray, be secured and then the tray is rolled into the pod (sideways). Upon arrival, the tray is retrieved from the pod, the car is released from the tray and can drive off.

Imagine even if the cars are Tesla's and can be battery swapped (to reduce weight) in that process!!

**Comment by menemCarlitos** [comment]
Yes, that would be a quite good solution.
I don't know programming though.

**Comment by Australianspacey** [comment]
Or even better self-producing tesla's that charge and restore the life of other vehicles present, suficient use of sustainable electric tesla's self sufficiency is always good when other task are needed to be carried out.:)
